FROM node:18-alpine
WORKDIR /app

COPY package*.json ./

# make sure registry is public
RUN npm config set registry https://registry.npmjs.org/
RUN npm install --registry=https://registry.npmjs.org/

# install dependencies
RUN npm install

# copy frontend source code
COPY . ./

EXPOSE 3000
CMD ["npm", "start"]